### ISSUE TITLE
Inconsistent Virtual Device Addressing

### ISSUE THREAD

**Issue by rkrishnasanka** [CIDARLAB/Neptune-Peripheral-Manager#7]
Virtual Device Addressing is inconsistent with the rest of the addressing system.

If a virtual device is name `vdevice` then the following js code should be enough to write the data to the file:

```
socket.emit('vdevice', COMMAND_TO_SEND);
```

**Comment by anishasthana** [comment]
So the relevant serial com events are below:
socket.emit('send message', data)
socket.emit('virtual message', data)

data is an array with two elements - the first element is the name of the device, and the second element is the command to be sent.
